### ISSUE TITLE
Build a Responsive Navigation Bar with Mobile Menu Toggle

### ISSUE THREAD

**Issue by monster0318** [monster0318/Curso-web#5]
---

**Description:**
Let's add a responsive navigation bar to our course project! This navbar will include:

* A site logo or name
* Navigation links (Home, About, Contact)
* A mobile-friendly toggle (hamburger menu) using JavaScript

The goal is to make it clean, responsive, and educational for beginners.

---

**Tasks:**

* [ ] Create `navbar.html` or add the navbar to the main page
* [ ] Style the navbar using flexbox or CSS grid
* [ ] Hide the menu on smaller screens and show a hamburger icon
* [ ] Use JavaScript to toggle the menu visibility on mobile
* [ ] Add transition/animation for smooth toggle effect

---

**Code Snippet (HTML + CSS + JS):**

```html
<!-- index.html -->
<header class="navbar">
  <h1 class="logo">Curso Web</h1>
  <nav class="nav-links" id="navLinks">
    <a href="#">Home</a>
    <a href="#">About</a>
    <a href="#">Contact</a>
  </nav>
  <button class="menu-toggle" onclick="toggleMenu()">☰</button>
</header>
```

```css
/* styles.css */
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background: #222;
  color: white;
}

.nav-links {
  display: flex;
  gap: 1rem;
}

.menu-toggle {
  display: none;
  background: none;
  color: white;
  font-size: 1.5rem;
  border: none;
}

@media (max-width: 768px) {
  .nav-links {
    display: none;
    flex-direction: column;
    background: #333;
    position: absolute;
    top: 60px;
    right: 0;
    padding: 1rem;
  }
  .menu-toggle {
    display: block;
  }
}
```

```js
// script.js
function toggleMenu() {
  const nav = document.getElementById("navLinks");
  nav.style.display = nav.style.display === "flex" ? "none" : "flex";
}
```

---

**Acceptance Criteria:**

* [ ] Navbar is visible on all screen sizes
* [ ] On mobile, the hamburger menu toggles nav links
* [ ] Code is clean and commented for learning purposes
* [ ] Works across major browsers and screen sizes

---

**Labels:**
`feature`, `frontend`, `html-css-js`, `beginner`, `responsive`

---
